[tool.poetry]
name = "django-cryptofeed-werks"
version = "0.1.0"
description = "Django Cryptofeed Werks aggregates candlesticks using tick data from financial exchanges"
authors = ["Alex <globophobe@gmail.com>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/globophobe/django-cryptofeed-werks"
repository = "https://github.com/globophobe/django-cryptofeed-werks"
keywords = ["django", "cryptocurrency", "candles", "trading"]
classifiers = ["Development Status :: 4 - Beta", "Operating System :: OS Independent"]
packages = [{ include = "cryptofeed_werks" }]

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
django-filter = "*"
djangorestframework = "*"
django-storages = "*"
httpx = "*"
pandas = "*"
pyarrow = "*"
randomname = "*"

[tool.poetry.dev-dependencies]
black = "*"
channels = "*"
django-semantic-admin = "*"
django-storages = {version = "*", extras = ["google"]}
flake8 = "*"
invoke = "*"
isort = "*"
mkdocs = "*"
psycopg2-binary = "*"
python-decouple = "*"
telegram-send = "*"
uvicorn = "*"
whitenoise = "*"


[tool.isort]
known_first_party = ["cryptofeed_werks"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
